import { describe, expect, it } from "vitest";

import { generateConfigModule } from "../build/codegen";

describe("generateConfigModule", () => {
  it("generates a valid ES module for base config", () => {
    const output = generateConfigModule({});
    expect(output).toContain("// Auto-generated by eslint-config-setup");
    expect(output).toContain("// @ts-nocheck");
    expect(output).toContain("export default [");
    expect(output).toContain('import tseslint from "typescript-eslint"');
  });

  it("includes base rules block", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/base"');
    expect(output).toContain("projectService: true");
  });

  it("includes JS compat override", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/js-compat"');
    expect(output).toContain("**/*.{js,mjs,cjs}");
  });

  it("includes test override", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/tests"');
    expect(output).toContain("**/*.test.{ts,tsx}");
  });

  it("includes testing-library block", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/tests-testing-library"');
    expect(output).toContain("testing-library");
  });

  it("includes e2e override", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/e2e"');
    expect(output).toContain("**/*.spec.ts");
  });

  it("includes stories override", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/stories"');
    expect(output).toContain("**/*.stories.{ts,tsx}");
  });

  it("includes JSON blocks", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/json"');
    expect(output).toContain('"eslint-config-setup/jsonc"');
  });

  it("includes package.json block", () => {
    const output = generateConfigModule({});
    expect(output).toContain('"eslint-config-setup/package-json"');
  });

  it("includes markdown block", () => {
    const output = generateConfigModule({});
    expect(output).toContain("mdxPlugin.flat");
  });

  it("adds react imports and settings when react is enabled", () => {
    const output = generateConfigModule({ react: true });
    expect(output).toContain("globals.browser");
    expect(output).toContain("ecmaFeatures: { jsx: true }");
    expect(output).toContain("eslintReactPlugin");
  });

  it("does not emit legacy aliases for semantically different React rules", () => {
    const output = generateConfigModule({ react: true });
    expect(output).toContain('"react/no-forward-ref": "warn"');
    expect(output).toContain('"react/no-prop-types": "error"');
    expect(output).not.toContain(
      '"forward-ref-uses-ref": [core, "no-forward-ref"]',
    );
    expect(output).not.toContain('"prop-types": [core, "no-prop-types"]');
  });

  it("does not include react settings when react is disabled", () => {
    const output = generateConfigModule({});
    expect(output).not.toContain("globals.browser");
    expect(output).not.toContain("eslintReactPlugin");
  });

  it("adds node globals when node is enabled", () => {
    const output = generateConfigModule({ node: true });
    expect(output).toContain("globals.node");
  });

  it("adds OxLint block when oxlint is enabled", () => {
    const output = generateConfigModule({ oxlint: true });
    expect(output).toContain('"eslint-config-setup/oxlint"');
    expect(output).toContain("oxlintPlugin");
  });

  it("does not include OxLint block when oxlint is disabled", () => {
    const output = generateConfigModule({});
    expect(output).not.toContain("oxlintPlugin");
  });

  it("adds OxLint react configs when react+oxlint", () => {
    const output = generateConfigModule({ react: true, oxlint: true });
    expect(output).toContain('"eslint-config-setup/oxlint-react"');
    expect(output).toContain('"eslint-config-setup/oxlint-jsx-a11y"');
  });

  it("adds OxLint node config when node+oxlint", () => {
    const output = generateConfigModule({ node: true, oxlint: true });
    expect(output).toContain('"eslint-config-setup/oxlint-node"');
  });

  it("adds package-json AI rules when ai is enabled", () => {
    const output = generateConfigModule({ ai: true });
    expect(output).toContain('"eslint-config-setup/package-json-ai"');
    expect(output).toContain("package-json/order-properties");
  });

  it("does not add React AI overrides without react flag", () => {
    const output = generateConfigModule({ ai: true });
    expect(output).not.toContain('"react/no-context-provider": "error"');
    expect(output).not.toContain('"react/prefer-read-only-props": "error"');
  });

  it("adds React AI overrides only for react+ai configs", () => {
    const output = generateConfigModule({ react: true, ai: true });
    expect(output).toContain('"react/no-context-provider": "error"');
    expect(output).toContain('"react/prefer-read-only-props": "error"');
    expect(output).toContain('"react-hooks/void-use-memo": "error"');
  });

  it("does not add package-json AI rules without ai flag", () => {
    const output = generateConfigModule({});
    expect(output).not.toContain('"eslint-config-setup/package-json-ai"');
  });

  it("generates valid JS syntax (no trailing commas in arrays)", () => {
    const output = generateConfigModule({ react: true, node: true, ai: true });
    // Should end with a closing bracket
    expect(output.trim()).toMatch(/\]$/);
  });

  it("produces deterministic output", () => {
    const a = generateConfigModule({ react: true });
    const b = generateConfigModule({ react: true });
    expect(a).toBe(b);
  });

  it("generates different output for different options", () => {
    const base = generateConfigModule({});
    const react = generateConfigModule({ react: true });
    expect(base).not.toBe(react);
  });

  it("only includes active rules (no 'off' rules in base)", () => {
    const output = generateConfigModule({});
    // The base block should not contain rules set to "off"
    const baseMatch = output.match(
      /name: "eslint-config-setup\/base"[\s\S]*?rules: \{([\s\S]*?)\}/,
    );
    if (baseMatch) {
      expect(baseMatch[1]).not.toContain('"off"');
    }
  });
});
